V1.x.x SSR-2366 Edit Table component proto
kintone-labs/kintone-ui-component pull request #1091
Opened 2022-07-06 01:47 UTC by voduchau

2022-08-19 07:25 UTC, TomokoMiyake requested changes

2022-08-19 07:25 UTC, TomokoMiyake commented on src/base/constant.ts
> +    IS_NOT_ARRAY: "data' property is not array.",
```suggestion
    IS_NOT_ARRAY: "'data' property is not array.",
```

2022-08-29 04:38 UTC, TomokoMiyake requested changes

2022-08-29 04:38 UTC, TomokoMiyake commented on src/table/index.stories.js
> +  const text = new TextArea({ value: dataCell });
```suggestion
const renderAge = (cellData, rowData) => {
  const text = new TextArea({ value: cellData });
```

2022-08-29 04:38 UTC, TomokoMiyake commented on src/table/type.ts
> +  dataRow: object,
```suggestion
  cellData: any,
  rowData: object,
```

2022-09-13 03:02 UTC, TomokoMiyake requested changes

2022-09-13 03:02 UTC, TomokoMiyake commented on src/table/index.ts
> +  validateFieldRequiedInColumnTable,
```suggestion
  validateFieldRequiredInColumnTable,
```

2022-09-13 03:02 UTC, TomokoMiyake commented on src/table/index.ts
> +      if (!validateFieldRequiedInColumnTable(this.columns)) {
```suggestion
      if (!validateFieldRequiredInColumnTable(this.columns)) {
```

2022-09-13 05:25 UTC, TomokoMiyake approved these changes
LGTM!

2022-09-21 14:36 UTC, nmanhit commented on src/base/validator.ts
> +    const containField = "field" in column;
```
if (!column.hasOwnProperty("field")) return false;
```
The ``hasOwnProperty`` will be faster than the ``in``

2022-09-21 14:41 UTC, nmanhit commented on src/base/validator.ts
> +  const valueArr = columns.map(function (item: any) {
the code written in the short format
```const valueArr = columns.map((item) => item.field);```

2022-09-21 14:42 UTC, nmanhit commented on src/base/validator.ts
> +  if (!Array.isArray(data)) return false;
```return Array.isArray(data)```

2022-09-21 14:45 UTC, nmanhit commented on src/table/index.ts
> +      return html`
return this.columns.length === 0 ? null : html` .....`

2022-09-29 01:21 UTC, nmanhit commented on src/table/style.ts
> +    .kuc-table__table__header__cell__label {
We don't use this class

2022-10-10 06:58 UTC, nmanhit commented on src/table/index.ts
> +      return html`
return !this.columns || this.columns.length < 1
        ? html`
            <table class="kuc-table__table">
              <caption
                class="kuc-table__table__label"
                ?hidden="${!this.label}"
              >
                ${this.label}
              </caption>
            </table>
          `
        : html` .....`

2022-10-10 07:15 UTC, nmanhit commented on src/table/index.stories.js
> +      { label: "sample1", value: "sample1" },
```
{ label: "Orange", value: "orange" },
{ label: "Banana", value: "banana" },
{ label: "Tomato", value: "tomato" },
```

2022-11-23 02:34 UTC, nmanhit commented on src/table/index.ts
> +        errorMessage = errorColumns;
return errorColumns

2022-11-23 02:35 UTC, nmanhit commented on src/table/index.ts
> +        errorMessage = ERROR_MESSAGE.DATA_TABLE.IS_NOT_ARRAY;
return ERROR_MESSAGE.DATA_TABLE.IS_NOT_ARRAY;

2022-11-23 02:35 UTC, nmanhit commented on src/table/index.ts
> +      return errorMessage;
return "";

2022-12-02 01:36 UTC, merged