SSR-2360 User guide for Custom CSS
kintone-labs/kintone-ui-component pull request #1134
Opened 2022-08-23 09:31 UTC by voduchau

2022-08-24 00:32 UTC, TomokoMiyake requested changes
The next version will be v1.5.0, so please change to that.

2022-08-24 01:46 UTC, voduchau commented on docs/document/docs/getting-started/custom-css.md
> +**Kintone UI Component** provide some Custom CSS properties for each component by using [CSS inheritance](#css-inheritance) and [CSS variables and custom properties](#css-variables-and-custom-propert
themable element meaning an element that we can customize its css.
I will change "themable" to "customizable".

2022-08-24 01:48 UTC, voduchau commented on docs/document/docs/getting-started/custom-css.md
> +KUC will publicize some properties for each element, based on that users can customize css easily (_For now we will publicize some properties for **Button** and **Text** component first_).
>What is the meaning of "publicize" in this case?
I change "publicize" to "publish".

>I think it is good not to mention the component names.
Ok, I remove it

2022-08-24 02:55 UTC, voduchau commented on docs/document/docs/getting-started/custom-css.md
> +**Kintone UI Component** provide some Custom CSS properties for each component by using [CSS inheritance](#css-inheritance) and [CSS variables and custom properties](#css-variables-and-custom-propert
I also change to v1.5.0.
Thank you

2022-08-24 03:05 UTC, TomokoMiyake commented on docs/document/docs/getting-started/custom-css.md
> +**Kintone UI Component** provide some Custom CSS properties for each component by using [CSS inheritance](#css-inheritance) and [CSS variables and custom properties](#css-variables-and-custom-propert
Got it, thank you!

2022-08-24 06:30 UTC, TomokoMiyake requested changes
Please update docs/document/components.

2022-08-24 06:36 UTC, TomokoMiyake requested changes

2022-08-24 06:36 UTC, TomokoMiyake commented on docs/document/docs/getting-started/custom-css.md
> +  }
You are using "my-element" before class name/id here.
And on Sample Code of Text, you are directly using class name/id as element selector.
I think it's better to unify it.

2022-08-25 04:14 UTC, TomokoMiyake approved these changes
LGTM!

2022-08-25 07:18 UTC, huuchi1778 commented on docs/document/docs/getting-started/custom-css.md
> +**Kintone UI Component (KUC)** provides some Custom CSS properties for each component by using [CSS inheritance](#css-inheritance) and [CSS variables and custom properties](#css-variables-and-custom-
```suggestion
**Kintone UI Component (KUC)** provides some Custom CSS properties for each component by using [CSS inheritance](#css-inheritance), [CSS variables and custom properties](#css-variables-and-custom-properties) together. It's easy to create customizable elements by applying CSS selectors to customize CSS custom properties. Tree-based and per-instance theming are straightforward to apply.
```

2022-08-25 07:50 UTC, huuchi1778 reviewed
Please have a look at my suggestions.
Thank you!

2022-08-25 07:50 UTC, huuchi1778 commented on docs/document/docs/getting-started/custom-css.md
> +All CSS custom properties (`--custom-property-name`) inherit. You can use this to make your component's styles configurable from outside.
```suggestion
All CSS custom properties (`--custom-property-name`) inherit their value from their parent. You can use this to make your component's styles configurable from the outside.
```
How about this to make the sentence clearer?

2022-08-25 07:50 UTC, huuchi1778 commented on docs/document/docs/getting-started/custom-css.md
> +KUC will publish some properties for each element, based on that users can customize CSS easily.
```suggestion
KUC will publish some properties for each element and based on that, users can easily customize CSS properties of the element.
```

2022-08-25 07:50 UTC, huuchi1778 commented on docs/document/docs/getting-started/custom-css.md
> +You can set the value for `--my-background` by using the CSS element selector:
```suggestion
You can set the value for `--my-background` by using the CSS selectors:
```
It seems like you can use not only element selectors but other CSS selectors in general.

2022-08-25 07:50 UTC, huuchi1778 commented on docs/document/docs/getting-started/custom-css.md
> +> You can find the list of Custom CSS properties in the **Custom CSS** section on each component page.
```suggestion
> You can find a list of the Custom CSS properties in the **Custom CSS** section on each component page.
```

2022-08-26 03:49 UTC, merged