SSR-2825_create attachment user guide
kintone-labs/kintone-ui-component pull request #1209
Opened 2022-11-15 02:16 UTC by h000780

## Why

## What

## How to test

## Checklist

- [ ] Read CONTRIBUTING.md([for v1](https://github.com/kintone-labs/kintone-ui-component/master/CONTRIBUTING.md), [for v0](https://github.com/kintone-labs/kintone-ui-component/v0_dev/CONTRIBUTING.md))
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed lint and test command.

2022-11-16 08:39 UTC, dong0 commented on docs/document/docs/components/desktop/attachment.md
> +``` javascript
Please refer to the document of other components to add "const Kuc = Kucs['1.x.x'];" here.

2022-11-16 08:39 UTC, dong0 commented on docs/document/docs/components/desktop/attachment.md
> +  files: [{name: "file.txt", size: "150"}],
Please use ' for uniformity.

2022-12-16 11:03 UTC, TomokoMiyake requested changes
Please update following the review comments.

2022-12-16 11:06 UTC, TomokoMiyake requested changes

2022-12-16 11:06 UTC, TomokoMiyake commented on docs/document/website/versioned_docs/version-1.8.0/components/desktop/attachment.md
> +const space = kintone.app.record.getSpaceElement('space');
```suggestion
const Kuc = Kucs['1.x.x'];

const space = kintone.app.record.getSpaceElement('space');

```

2022-12-16 11:06 UTC, TomokoMiyake commented on docs/document/website/versioned_docs/version-1.8.0/components/desktop/attachment.md
> +  files: [{name: 'file.txt', size: '150'}],
How about adding File object pattern?

2022-12-19 05:16 UTC, TomokoMiyake approved these changes
I fixed some more points. Please confirm it.

2022-12-19 08:56 UTC, cy-kaneko commented on docs/document/website/translated_docs/ja/version-1.8.0/components/desktop/attachment.md
> +| change | function | ファイルが変更された時のイベントハンドラー | 引数には Event の event オブジェクトをとる<br>event.detail で以下の値を受け取ることができる<li>add-file（ファイル追加された時にトリガーされる）<ul><li>event.detail.type: "add-file"<li>event.detail.oldFil
表記ゆれ

> ファイルが変更された時のイベントハンドラー 

ファイルが変更された時のイベントハンドラ

2022-12-20 06:30 UTC, merged