user guide for read only table
kintone-labs/kintone-ui-component pull request #1211
Opened 2022-11-16 02:28 UTC by nmanhit

## Why

## What

## How to test

## Checklist

- [ ] Read CONTRIBUTING.md([for v1](https://github.com/kintone-labs/kintone-ui-component/master/CONTRIBUTING.md), [for v0](https://github.com/kintone-labs/kintone-ui-component/v0_dev/CONTRIBUTING.md))
- [ ] Updated documentation if it is required.
- [ ] Added tests if it is required.
- [ ] Passed lint and test command.

2022-11-16 10:04 UTC, voduchau commented on docs/document/website/versioned_docs/version-1.8.0/components/desktop/readonly-table.md
> +```
add empty line end of this file

2022-11-16 10:05 UTC, voduchau commented on docs/document/website/versioned_docs/version-1.8.0/components/desktop/readonly-table.md
> +      field: "index",
In sample code, please use single qoutes

2022-11-16 10:05 UTC, voduchau commented on docs/document/website/versioned_docs/version-1.8.0/components/desktop/readonly-table.md
> +```
please check and update at docs/components/desktop/readonly-table.js too

2022-11-16 10:09 UTC, voduchau commented on docs/document/docs/components/desktop/readonly-table.md
> +| Column.visible | Boolean | true | Show/Hide the column | |
Separate column property to a table

2022-12-16 07:41 UTC, TomokoMiyake requested changes
Please update following review comments.

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +| columns | Array\<[Columns](#column)\> | []  | Column data of the component. | Throw an error if the `columns` is not an array. |
```suggestion
| columns | Array\<[Column](#column)\> | []  | Column data of the component. | Will result an error if the value of `columns` is not an array. |
```

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +| data | Array\<object\> | []  | Row data of the component. | Throw an error if the `data` is not an array. |
```suggestion
| data | Array\<object\> | []  | Row data of the component | Will result an error if the value of `data` is not an array. |
```

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +| className | string | ""  | Component class name. | |
```suggestion
| className | string | ""  | Component class name | |
```

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +| id | string | ""  | Component id name. | |
```suggestion
| id | string | ""  | Component id name | |
```

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +| field | string | ""  | Key of the data object. | |
```suggestion
| field | string | ""  | Key of the data object | |
```

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +| title | string | ""  | Header name of the column. | |
```suggestion
| title | string | ""  | Header name of the column | |
```

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +| visible | boolean |  true  | Show/Hide the column. | |
```suggestion
| visible | boolean |  true  | Show/Hide the column | |
```

2022-12-16 07:41 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
>  ```
Please update with below including every props.

```
const Kuc = Kucs['1.x.x'];

const space = kintone.app.record.getSpaceElement('space');

const readOnlyTable = new ReadOnlyTable({
  label: 'ReadOnlyTable',
  columns: [
    {
      title: 'Number',
      field: 'index',
    },
    {
      title: 'City',
      field: 'name',
    },
    {
      title: 'Country',
      field: 'country',
    },
    {
      title: 'Population',
      field: 'population',
    },
    {
      title: 'Coordinates',
      field: 'coordinates',
    }
  ],
  data: [
    {
      index: '1',
      name: 'HoChiMinh',
      country: 'Vietnam',
      population: '8,371,000',
      coordinates: '10.762622, 106.660172',
    },
    {
      index: '2',
      name: 'Tokyo',
      country: 'Japan',
      population: '14,000,000',
      coordinates: '35.689487, 139.691711',
    },
    {
      index: '3',
      name: 'New York',
      country: 'USA',
      population: '8,400,000',
      coordinates: '40.712776, -74.005974',
    }
  ],
  className: 'sample-class',
  id: 'sample-id',
  visible: true,
  pagination: true,
  rowsPerPage: 3,
});
space.appendChild(readOnlyTable);
```

2022-12-16 08:19 UTC, TomokoMiyake requested changes

2022-12-16 08:19 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
```suggestion

> Please check the [package installation](../../getting-started/quick-start.md#installation) method first.
```

2022-12-16 10:50 UTC, TomokoMiyake requested changes

2022-12-16 10:50 UTC, TomokoMiyake commented on docs/document/docs/components/desktop/readonly-table.md
> +#### Column
How about writing inside "### Property" like this?
Column.field, Column.title, etc.
https://kintone-ui-component.netlify.app/docs/en/components/desktop/dropdown

2022-12-20 03:03 UTC, TomokoMiyake approved these changes
I updated for review.
Please confirm with it.

2022-12-20 06:28 UTC, merged