v1.0.4_SSR-1484 Unit test coverage with up to 90%
kintone-labs/kintone-ui-component pull request #545
Opened 2021-06-09 05:50 UTC by nmanhit

2021-06-16 00:44 UTC, nmanhit commented on src/dialog/test/changeEvent.test.ts
> +    await triggerFocusFor(itemsEl);
i think it do not duplicate, kuc-dialog__last-dummy and kuc-dialog__first-dummy is different

2021-06-16 00:54 UTC, nmanhit commented on src/readonly-table/test/data.test.ts
> +      // @ts-ignore
@ts-expect-error can not assignable to type string[]
container.data = [null];

2021-06-24 02:52 UTC, trung-doan requested changes

2021-06-24 02:52 UTC, trung-doan commented on src/mobile/notification/test/changeEvent.test.ts
> +    await expect(container.classList.contains("onclick")).to.be.true;
@nmanhit 
I think we change the expectation to popup closed after clicked close button.

2021-06-24 02:52 UTC, trung-doan commented on src/multichoice/test/changeEvent.test.ts
> +
@nmanhit 
Is it has been corresponded?

2021-06-24 02:52 UTC, trung-doan commented on src/readonly-table/test/data.test.ts
> +      // @ts-ignore
@nmanhit 
I have tried and it can work normally.
Could you please check it again?

2021-06-24 02:52 UTC, trung-doan commented on src/textarea/test/changeEvent.test.ts
> +
@nmanhit 
>This logic for checking changing value, please move it into case which have changing value.

Is it has been coressponded?

>For mousedown mousemove mouseup, it should be adding corresponding expectations.

If it is difficult to decide expectation now, could you please add below message:
// TODO: Update expect() logic.

2021-06-28 03:57 UTC, merged