v1.0.4_SSR-1375 mobile dropdown
kintone-labs/kintone-ui-component pull request #552
Opened 2021-06-21 07:31 UTC by nmanhit

2021-06-23 10:02 UTC, josh-vo requested changes

2021-06-23 10:02 UTC, josh-vo commented on src/mobile/dropdown/index.ts
> +            aria-invalid="true"
The "aria-required" and "aria-invalid" have condition to set "true". So, could you please update code following spec?

2021-06-29 07:34 UTC, josh-vo approved these changes

2021-06-30 01:39 UTC, trung-doan requested changes

2021-06-30 01:39 UTC, trung-doan commented on src/mobile/dropdown/test/className.test.ts
> +    it("className default prop is null", async () => {
@nmanhit 
Please remove `className` and change the `title` to the same content with expectation.
Ex: `it("should be set to empty string when initializing without props option")`

2021-06-30 01:39 UTC, trung-doan commented on src/mobile/dropdown/test/className.test.ts
> +    it("className default prop set successfully", async () => {
@nmanhit 
Please remove `className` and change the `title` to the same content with expectation.
Ex: `it("should be equal \"options-class\" string when initializing className with \"options-class\" value ")`

2021-06-30 01:39 UTC, trung-doan commented on src/mobile/dropdown/test/className.test.ts
> +    it("className prop replace successfully'", async () => {
@nmanhit 
Please remove `className` and change the `title` to the same content with expectation.
Ex: `it("it should be replace by \"replace-class\" when changing by setter")`

2021-06-30 01:39 UTC, trung-doan commented on src/mobile/dropdown/test/className.test.ts
> +    it("className default prop set to null", async () => {
@nmanhit 
Please remove this unneeded case.

2021-06-30 01:39 UTC, trung-doan commented on src/mobile/dropdown/test/className.test.ts
> +    it("className prop set to null", async () => {
@nmanhit 
Please remove this unneeded case.

2021-07-13 02:14 UTC, closed without merging